### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by shubhamispro123** [jawikas/memefi-bot#5]
Failed to login, status code: 403
[2024-09-11 00:32:52] Failed with status 403, retrying

tried getting new query still this issue , it was working fine before memefi  server down
![Screenshot (48)](https://github.com/user-attachments/assets/25bbddb8-7819-49ae-b653-9c1ad942d2c4)

**Comment by Pawansingh333** [comment]
same and please add spin feature in your bot thanks

**Comment by LahHalah** [comment]
same

**Comment by nxuanthanh** [comment]
same, please fix it now

**Comment by shubhamispro123** [comment]
thank you now its fixed
